components/home.js
styles/home.css
styles/styles.css

Hi I've updated the homepage and added new fonts in styels.css, would be much appreciated if someone check this out!

Add new fonts in styles.css and update homepage

---

confirmed_profile.html
contact.html
styles/confirmed.css
styles/contact-form.css

Removed dependencies on home.css for contact.html and confirmed_profile.html.  They should now render correctly.

Fixed Pages

---

fuelQuoteForm.html
orderSummary.php
styles/fuelQuoteForm.css
styles/orderSummary.css

Created orderSummary .php, and .css.  Updated fuelQuoteForm .html and .css such that they now link to orderSummary.php.

orderSummary.php & updates to fuelQuoteForm

---

components/orderConfirmation.js
components/orderSummary.js
orderConfirmation.html
orderSummary.php
styles/orderConfirmation.css

Simple fix to get orderConfirmation working.

Fix to orderConfirmation

---

Login_Page.html
register.html

Fixed Login/Registration Pages.  Also fixed typos and adjusted text.

Fixed Login/Registration Pages

---

orderConfirmation.html
styles/orderConfirmation.css

Fixed css style linkage and html text.

Adjusting Order Confirmation

---

components/home.js
components/userProfile.js

The home page "Buy Now" button links to the old .html instead of .php.
Profile Manager links to orderSummary.php instead of confirmed_profile.html.
In Profile Manager, the email field was not of type email so it didn't validate for email.

FIXED SOME LINKS & BUGS

---

contact.html
orderSummary.php

Contact fields did not validate input.
orderSummary.php Cancel button now returns home correctly.

Fixed more bugs and links

---

about.html
components/about.js
components/home.js
styles/about.css

About page

---

employment.html
styles/employment.css

Created employment.html and employment.css

Employment Page

---

components/home.js

Linked employment.html to index.html

Fixed employment link on home page

---

server/clientsList.php
server/login.php
server/loginManager.php
server/logout.php
server/registrationManager.php
server/test.php
src/client.php
src/hcUser.php

Added:
(src folder)
client.php
hcUser.php
(server folder)
-clientsList.php (hardcoded list of client to log in) -login.php
-logout.php
-loginManager.php
-registrationManager.php
This provides the basic skeleton to implement our user authentication and registration without a database.  We will switch from hcUser to the alternative user class once that's fixed.

Basic hardcoded Login Functionality and Related

---

about.php
components/nav-bar.php
confirmed_profile.php
contact.php
editUserProfile.php
employment.php
fuelQuoteForm.php
orderConfirmation.html
orderSummary.php

Affected files:
index.php
contact.php
about.php
employment.php
editUserProfile.php
fuelQuoteForm.php
confirmed_profile.php
orderSummary.php
Double check that everything is listed.

Improving Session Setup

---

.gitignore
components/loginConfirmation.js
fuelQuoteForm.php
orderSummary.php
server/clientsList.php

- Added session variables to fuelQuoteForm.php and orderSummary.php to use login information.
- Fixed the redirection from orderSummary.php to the wrong files.  The confirm and cancel buttons now point to the appropriate .php pages instead of our original .html pages.
- Received help from @VysePresident in fixing the problems with login information.  Login information is now retained after signing in.

Isaacb php3

---

components/loginConfirmation.js
loginConfirmation.php
server/loginStart.php
src/client.php
src/hcUser.php
src/loginManager.php
src/registrationManager.php

-Small changes to registrationManager.php in src.
-Fixing loginManager.php and client.php to work with the new database information.

Login works correctly with both database tables

---

components/loginConfirmation.js

Fixing Login Transition Time

---

customer_history_page.php
src/connection.php

Converted customer_history_page.html to customer_history_page.php;
Added connection.php;
Implemented basic MySQL functionality to the preexisting table.
Still requires session variables.

Basic Functionality

---

.gitignore
src/loginManager.php
tests/loginManagerTest.php

Login improvements - using up to date login information in unit test.

Login improvements

---

index.php

Fix Session Start - adjust php positioning.

Fix Session Start

---

Login_Page.php
about.php
components/nav-bar.php
confirmed_profile.php
contact.php
customer_history_page.php
editUserProfile.php
employment.php
fuelQuoteForm.php
newRow.php
orderConfirmation.php
orderSummary.php
registration.php

Fixing session_start() across more pages + FuelQuote now inserts data into database.

Fixed session_start() + fuelQuote

---

components/nav-bar.php
server/pricingModule.php

Fix to orderSummary session_start()

Fix to orderSummary session_start()

---

newRow.php

Updated newRow.php GLHF -  probably doesn't need the bloody mess.

Updated newRow.php
